# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/c/Xilinx/Projects/DFT_v/DFT_v.srcs/sources_1/bd/design_1/ip/design_1_xbar_2_1/design_1_xbar_2.xci
# IP: The module: 'design_1_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/c/Xilinx/Projects/DFT_v/DFT_v.gen/sources_1/bd/design_1/ip/design_1_xbar_2_1/design_1_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /mnt/c/Xilinx/Projects/DFT_v/DFT_v.srcs/sources_1/bd/design_1/ip/design_1_xbar_2_1/design_1_xbar_2.xci
# IP: The module: 'design_1_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/c/Xilinx/Projects/DFT_v/DFT_v.gen/sources_1/bd/design_1/ip/design_1_xbar_2_1/design_1_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
