# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_2/design_1_rst_ps7_0_100M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_2 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_6/design_1_xbar_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_6 || ORIG_REF_NAME==design_1_xbar_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_3/design_1_ps7_0_axi_periph_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_3 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sadd_0_1/design_1_sadd_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_sadd_0_1 || ORIG_REF_NAME==design_1_sadd_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_2/design_1_axi_dma_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_2 || ORIG_REF_NAME==design_1_axi_dma_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_7/design_1_xbar_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_7 || ORIG_REF_NAME==design_1_xbar_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_4/design_1_axi_mem_intercon_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_4 || ORIG_REF_NAME==design_1_axi_mem_intercon_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_1_1/design_1_axi_dma_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_1_1 || ORIG_REF_NAME==design_1_axi_dma_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_1_3/design_1_axi_mem_intercon_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_1_3 || ORIG_REF_NAME==design_1_axi_mem_intercon_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# XDC: d:/WSLg/HLS/Lab3/sadd_v/project_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
